hw_5 is done
Dorstol/hillel_hm pull request #6
Opened 2022-07-13 12:48 UTC by Dorstol

2022-07-14 07:27 UTC, Seclorum12 requested changes
Привіт, цілком - непогано :smile: 
- Додай віртуальну середу
- Пофікси коменти

2022-07-14 07:27 UTC, Seclorum12 commented on hw_5/circle.py
> +print(circle.contains(point))
Оберни у конструкцію __mian__, щоб виклик не виконувався при імпорті.

2022-07-14 07:27 UTC, Seclorum12 commented on hw_5/circle.py
> +            return False
Це можливо спростити 
```suggestion
 return instance.x ** 2 + instance.y ** 2 <= self.radius ** 2
```
Але як метод враховує кординати самого кола?

2022-07-14 07:27 UTC, Seclorum12 commented on hw_5/main.py
> +        query_for_city += "WHERE " + " AND ".join(f"{k}=?" for k in _fields.keys()) + """
У циклі ключі беруться за замовчуванням.
```suggestion
     query_for_city += "WHERE " + " AND ".join(f"{k}=?" for k in _fields) + """
```

2022-07-14 07:27 UTC, Seclorum12 commented on hw_5/main.py
> +    if genre not in [g[0] for g in genres]:
Якщо це використовується `[g[0] for g in genres]` декілька разів, то має сенс винести у змінну.
- Не виконуюється декілька разів
- Якщо тобі треба щось додати у генерування, то не потрібно буде змінювати це у декількох місцях

2022-07-14 07:27 UTC, Seclorum12 commented on hw_5/main.py
> +    """
Не дуже красиве форматування.

2022-07-14 19:33 UTC, Bogdan-Shevchenko-DS commented
Дуже добре! 
- venv не пушеться тільки requirements.txt, або краще Pipfile
- Дуже гарно, що помітив несподівану поведінку з Opera! Зроби обробку помилок такого характеру и буде відмінно. (Opera) нічоко не повертає тому що у таблиці `invoice_items` розірван зв'язок. Там немає TrackId зі значенням 3451

2022-07-16 16:23 UTC, Seclorum12 approved these changes
Дуже добре!

2022-07-16 16:23 UTC, Seclorum12 commented on hw_5/main.py
> +        return '<h1>Opera is not a available genre, please choose another one.</h1>'
Це може бути не тільки Опера ) 
"Обробка такого типу помилок" - це мається на увази, якщо з БД нічого не повернулолсь, але сам жанр такие є.

2022-07-18 17:47 UTC, merged